// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/identitystore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListGroupsPaginator creates a new instance of MockListGroupsPaginator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListGroupsPaginator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListGroupsPaginator {
	mock := &MockListGroupsPaginator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListGroupsPaginator is an autogenerated mock type for the ListGroupsPaginator type
type MockListGroupsPaginator struct {
	mock.Mock
}

type MockListGroupsPaginator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListGroupsPaginator) EXPECT() *MockListGroupsPaginator_Expecter {
	return &MockListGroupsPaginator_Expecter{mock: &_m.Mock}
}

// HasMorePages provides a mock function for the type MockListGroupsPaginator
func (_mock *MockListGroupsPaginator) HasMorePages() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasMorePages")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockListGroupsPaginator_HasMorePages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasMorePages'
type MockListGroupsPaginator_HasMorePages_Call struct {
	*mock.Call
}

// HasMorePages is a helper method to define mock.On call
func (_e *MockListGroupsPaginator_Expecter) HasMorePages() *MockListGroupsPaginator_HasMorePages_Call {
	return &MockListGroupsPaginator_HasMorePages_Call{Call: _e.mock.On("HasMorePages")}
}

func (_c *MockListGroupsPaginator_HasMorePages_Call) Run(run func()) *MockListGroupsPaginator_HasMorePages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListGroupsPaginator_HasMorePages_Call) Return(b bool) *MockListGroupsPaginator_HasMorePages_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockListGroupsPaginator_HasMorePages_Call) RunAndReturn(run func() bool) *MockListGroupsPaginator_HasMorePages_Call {
	_c.Call.Return(run)
	return _c
}

// NextPage provides a mock function for the type MockListGroupsPaginator
func (_mock *MockListGroupsPaginator) NextPage(ctx context.Context, optFns ...func(*identitystore.Options)) (*identitystore.ListGroupsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, optFns)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NextPage")
	}

	var r0 *identitystore.ListGroupsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...func(*identitystore.Options)) (*identitystore.ListGroupsOutput, error)); ok {
		return returnFunc(ctx, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...func(*identitystore.Options)) *identitystore.ListGroupsOutput); ok {
		r0 = returnFunc(ctx, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identitystore.ListGroupsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...func(*identitystore.Options)) error); ok {
		r1 = returnFunc(ctx, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListGroupsPaginator_NextPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextPage'
type MockListGroupsPaginator_NextPage_Call struct {
	*mock.Call
}

// NextPage is a helper method to define mock.On call
//   - ctx
//   - optFns
func (_e *MockListGroupsPaginator_Expecter) NextPage(ctx interface{}, optFns ...interface{}) *MockListGroupsPaginator_NextPage_Call {
	return &MockListGroupsPaginator_NextPage_Call{Call: _e.mock.On("NextPage",
		append([]interface{}{ctx}, optFns...)...)}
}

func (_c *MockListGroupsPaginator_NextPage_Call) Run(run func(ctx context.Context, optFns ...func(*identitystore.Options))) *MockListGroupsPaginator_NextPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]func(*identitystore.Options))
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockListGroupsPaginator_NextPage_Call) Return(listGroupsOutput *identitystore.ListGroupsOutput, err error) *MockListGroupsPaginator_NextPage_Call {
	_c.Call.Return(listGroupsOutput, err)
	return _c
}

func (_c *MockListGroupsPaginator_NextPage_Call) RunAndReturn(run func(ctx context.Context, optFns ...func(*identitystore.Options)) (*identitystore.ListGroupsOutput, error)) *MockListGroupsPaginator_NextPage_Call {
	_c.Call.Return(run)
	return _c
}
