version: 0.2
    
phases:
  install:
    commands:
      # Update sam to latest version
      - wget -q https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      - unzip -q awscli-exe-linux-x86_64.zip
      - sudo ./aws/install --update
      - rm -rf ./aws  awscli-exe-linux-x86_64.zip

  pre_build: 
    commands:
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

  build:
    commands:
      # Assume correct role on the staging account
      - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn "${ProductionAcctCodePipelineCloudFormationRole}" --role-session-name "CloudFormationRole" --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))

      # Get FunctionArn from ssm paramter store
      - export $(printf "FunctionArn=%s" $(aws ssm get-parameter --name "/SSOSync/Staging/FunctionArn" --query "Parameter.[Value]" --output text))
      - echo "${FunctionArn}"

      # Create a changeset for the deployment
      - aws lambda invoke --function-name "${FunctionArn}" response.json

artifacts:
  files:
    - response.json


