all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_{{.InterfaceDir}}.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "mocks"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/awslabs/ssosync/internal/interfaces:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mocks_{{.InterfaceName}}.go"
  github.com/awslabs/ssosync/internal/http:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mocks_Http{{.InterfaceName}}.go"
      structname: "MockHttp{{.InterfaceName}}"
  github.com/awslabs/ssosync/internal/aws:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mocks_Aws{{.InterfaceName}}.go"
      structname: "MockAws{{.InterfaceName}}"
  github.com/awslabs/ssosync/internal/google:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mocks_Google{{.InterfaceName}}.go"
      structname: "MockGoogle{{.InterfaceName}}"