version: 0.2

env:
  exported-variables:
    - Project
    - Branch
    - Tag
    - CommitId
    - CommitMessage
    - CommitAuthor
    - CommitAuthorEmail
    - CommitHash
    - IsRelease        
    
phases:
  pre_build: 
    commands:
      # Fetch all dependencies
      - chmod +x cicd/gitvars/codebuild-git-wrapper.sh
      - cicd/gitvars/codebuild-git-wrapper.sh $GitRepo $GitBranch

  build:
    commands:
      - Branch=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'`
      - export Branch="${Branch#remotes/origin/}"
      - export Project="${APP_Name}"
      - export Tag=`git describe --tags --abbrev=0`
      - export CommitId="$(git log -1 --pretty=%H)"
      - export CommitMessage="$(git log -1 --pretty=%B)"
      - export CommitAuthor="$(git log -1 --pretty=%an)"
      - export CommitAuthorEmail="$(git log -1 --pretty=%ae)"
      - export CommitHash=`git rev-parse --short HEAD`

      - GitReleaseCommit=`git rev-list -n 1 tags/${Tag}`
      - echo $GitReleaseCommit
      - |
        if expr "${GitReleaseCommit}" : "${GitCommit}" >/dev/null; then
          IsRelease=true
        else
          IsRelease=false
        fi

      - |
        if expr "${Branch}" : "master" >/dev/null; then
          IsRelease=false
        fi

