package aws

import (
	"github.com/aws/aws-sdk-go/aws"
	awsclient "github.com/aws/aws-sdk-go/aws/client"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/identitystore"
	"github.com/aws/aws-sdk-go/service/identitystore/identitystoreiface"
)

type DryIdentityStore struct {
	*NullIdentityStore
	client identitystoreiface.IdentityStoreAPI
}

func NewDryIdentityStore(p awsclient.ConfigProvider, cfgs ...*aws.Config) identitystoreiface.IdentityStoreAPI {
	return &DryIdentityStore{
		NullIdentityStore: &NullIdentityStore{},
		client:            identitystore.New(p, cfgs...),
	}
}

// **********************
// Noop-success
// **********************

func (d *DryIdentityStore) CreateGroup(input *identitystore.CreateGroupInput) (*identitystore.CreateGroupOutput, error) {
	return &identitystore.CreateGroupOutput{
		GroupId:         aws.String(*input.DisplayName + "virtual"),
		IdentityStoreId: input.IdentityStoreId,
	}, nil
}

func (d *DryIdentityStore) CreateGroupMembership(input *identitystore.CreateGroupMembershipInput) (*identitystore.CreateGroupMembershipOutput, error) {
	return &identitystore.CreateGroupMembershipOutput{
		IdentityStoreId: input.IdentityStoreId,
		MembershipId:    aws.String(*input.GroupId + *input.MemberId.UserId + "virtual"),
	}, nil
}

func (d *DryIdentityStore) DeleteGroup(input *identitystore.DeleteGroupInput) (*identitystore.DeleteGroupOutput, error) {
	return &identitystore.DeleteGroupOutput{}, nil
}

func (d *DryIdentityStore) DeleteGroupMembership(input *identitystore.DeleteGroupMembershipInput) (*identitystore.DeleteGroupMembershipOutput, error) {
	return &identitystore.DeleteGroupMembershipOutput{}, nil
}

func (d *DryIdentityStore) DeleteUser(input *identitystore.DeleteUserInput) (*identitystore.DeleteUserOutput, error) {
	return &identitystore.DeleteUserOutput{}, nil
}

// **********************
// Passthrough methods
// **********************

func (d *DryIdentityStore) GetGroupMembershipId(input *identitystore.GetGroupMembershipIdInput) (*identitystore.GetGroupMembershipIdOutput, error) {
	return d.client.GetGroupMembershipId(input)
}

func (d *DryIdentityStore) IsMemberInGroups(input *identitystore.IsMemberInGroupsInput) (*identitystore.IsMemberInGroupsOutput, error) {
	return d.client.IsMemberInGroups(input)
}

func (d *DryIdentityStore) ListGroupMembershipsPages(input *identitystore.ListGroupMembershipsInput, fn func(*identitystore.ListGroupMembershipsOutput, bool) bool) error {
	return d.client.ListGroupMembershipsPages(input, fn)
}

func (d *DryIdentityStore) ListGroupsPages(input *identitystore.ListGroupsInput, fn func(*identitystore.ListGroupsOutput, bool) bool) error {
	return d.client.ListGroupsPages(input, fn)
}

func (d *DryIdentityStore) ListUsersPages(input *identitystore.ListUsersInput, fn func(*identitystore.ListUsersOutput, bool) bool) error {
	return d.client.ListUsersPages(input, fn)
}

type NullIdentityStore struct{}

var _ identitystoreiface.IdentityStoreAPI = &NullIdentityStore{}

// ********************
// Autogenerated minimaly compliant implementation
// func ... { return nil, nil }
// DO NOT ADD CODE BELOW THIS LINE
// ********************

func (n *NullIdentityStore) CreateGroup(input *identitystore.CreateGroupInput) (*identitystore.CreateGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) CreateGroupMembership(input *identitystore.CreateGroupMembershipInput) (*identitystore.CreateGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) CreateUser(input *identitystore.CreateUserInput) (*identitystore.CreateUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroup(input *identitystore.DeleteGroupInput) (*identitystore.DeleteGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroupMembership(input *identitystore.DeleteGroupMembershipInput) (*identitystore.DeleteGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteUser(input *identitystore.DeleteUserInput) (*identitystore.DeleteUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroup(input *identitystore.DescribeGroupInput) (*identitystore.DescribeGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroupMembership(input *identitystore.DescribeGroupMembershipInput) (*identitystore.DescribeGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeUser(input *identitystore.DescribeUserInput) (*identitystore.DescribeUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupId(input *identitystore.GetGroupIdInput) (*identitystore.GetGroupIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupMembershipId(input *identitystore.GetGroupMembershipIdInput) (*identitystore.GetGroupMembershipIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetUserId(input *identitystore.GetUserIdInput) (*identitystore.GetUserIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) IsMemberInGroups(input *identitystore.IsMemberInGroupsInput) (*identitystore.IsMemberInGroupsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroups(input *identitystore.ListGroupsInput) (*identitystore.ListGroupsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMemberships(input *identitystore.ListGroupMembershipsInput) (*identitystore.ListGroupMembershipsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListUsers(input *identitystore.ListUsersInput) (*identitystore.ListUsersOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateGroup(input *identitystore.UpdateGroupInput) (*identitystore.UpdateGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateUser(input *identitystore.UpdateUserInput) (*identitystore.UpdateUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupsPages(input *identitystore.ListGroupsInput, fn func(*identitystore.ListGroupsOutput, bool) bool) error {
	return nil
}

func (n *NullIdentityStore) ListGroupMembershipsPages(input *identitystore.ListGroupMembershipsInput, fn func(*identitystore.ListGroupMembershipsOutput, bool) bool) error {
	return nil
}

func (n *NullIdentityStore) ListUsersPages(input *identitystore.ListUsersInput, fn func(*identitystore.ListUsersOutput, bool) bool) error {
	return nil
}

func (n *NullIdentityStore) CreateGroupRequest(input *identitystore.CreateGroupInput) (*request.Request, *identitystore.CreateGroupOutput) {
	return nil, nil
}

func (n *NullIdentityStore) CreateGroupMembershipRequest(input *identitystore.CreateGroupMembershipInput) (*request.Request, *identitystore.CreateGroupMembershipOutput) {
	return nil, nil
}

func (n *NullIdentityStore) CreateUserRequest(input *identitystore.CreateUserInput) (*request.Request, *identitystore.CreateUserOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroupRequest(input *identitystore.DeleteGroupInput) (*request.Request, *identitystore.DeleteGroupOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroupMembershipRequest(input *identitystore.DeleteGroupMembershipInput) (*request.Request, *identitystore.DeleteGroupMembershipOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteUserRequest(input *identitystore.DeleteUserInput) (*request.Request, *identitystore.DeleteUserOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroupRequest(input *identitystore.DescribeGroupInput) (*request.Request, *identitystore.DescribeGroupOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroupMembershipRequest(input *identitystore.DescribeGroupMembershipInput) (*request.Request, *identitystore.DescribeGroupMembershipOutput) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeUserRequest(input *identitystore.DescribeUserInput) (*request.Request, *identitystore.DescribeUserOutput) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupIdRequest(input *identitystore.GetGroupIdInput) (*request.Request, *identitystore.GetGroupIdOutput) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupMembershipIdRequest(input *identitystore.GetGroupMembershipIdInput) (*request.Request, *identitystore.GetGroupMembershipIdOutput) {
	return nil, nil
}

func (n *NullIdentityStore) GetUserIdRequest(input *identitystore.GetUserIdInput) (*request.Request, *identitystore.GetUserIdOutput) {
	return nil, nil
}

func (n *NullIdentityStore) IsMemberInGroupsRequest(input *identitystore.IsMemberInGroupsInput) (*request.Request, *identitystore.IsMemberInGroupsOutput) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupsRequest(input *identitystore.ListGroupsInput) (*request.Request, *identitystore.ListGroupsOutput) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsRequest(input *identitystore.ListGroupMembershipsInput) (*request.Request, *identitystore.ListGroupMembershipsOutput) {
	return nil, nil
}

func (n *NullIdentityStore) ListUsersRequest(input *identitystore.ListUsersInput) (*request.Request, *identitystore.ListUsersOutput) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateGroupRequest(input *identitystore.UpdateGroupInput) (*request.Request, *identitystore.UpdateGroupOutput) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateUserRequest(input *identitystore.UpdateUserInput) (*request.Request, *identitystore.UpdateUserOutput) {
	return nil, nil
}

func (n *NullIdentityStore) CreateGroupWithContext(ctx aws.Context, input *identitystore.CreateGroupInput, opts ...request.Option) (*identitystore.CreateGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) CreateGroupMembershipWithContext(ctx aws.Context, input *identitystore.CreateGroupMembershipInput, opts ...request.Option) (*identitystore.CreateGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) CreateUserWithContext(ctx aws.Context, input *identitystore.CreateUserInput, opts ...request.Option) (*identitystore.CreateUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroupWithContext(ctx aws.Context, input *identitystore.DeleteGroupInput, opts ...request.Option) (*identitystore.DeleteGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteGroupMembershipWithContext(ctx aws.Context, input *identitystore.DeleteGroupMembershipInput, opts ...request.Option) (*identitystore.DeleteGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DeleteUserWithContext(ctx aws.Context, input *identitystore.DeleteUserInput, opts ...request.Option) (*identitystore.DeleteUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroupWithContext(ctx aws.Context, input *identitystore.DescribeGroupInput, opts ...request.Option) (*identitystore.DescribeGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeGroupMembershipWithContext(ctx aws.Context, input *identitystore.DescribeGroupMembershipInput, opts ...request.Option) (*identitystore.DescribeGroupMembershipOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) DescribeUserWithContext(ctx aws.Context, input *identitystore.DescribeUserInput, opts ...request.Option) (*identitystore.DescribeUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupIdWithContext(ctx aws.Context, input *identitystore.GetGroupIdInput, opts ...request.Option) (*identitystore.GetGroupIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetGroupMembershipIdWithContext(ctx aws.Context, input *identitystore.GetGroupMembershipIdInput, opts ...request.Option) (*identitystore.GetGroupMembershipIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) GetUserIdWithContext(ctx aws.Context, input *identitystore.GetUserIdInput, opts ...request.Option) (*identitystore.GetUserIdOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) IsMemberInGroupsWithContext(ctx aws.Context, input *identitystore.IsMemberInGroupsInput, opts ...request.Option) (*identitystore.IsMemberInGroupsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupsWithContext(ctx aws.Context, input *identitystore.ListGroupsInput, opts ...request.Option) (*identitystore.ListGroupsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsWithContext(ctx aws.Context, input *identitystore.ListGroupMembershipsInput, opts ...request.Option) (*identitystore.ListGroupMembershipsOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListUsersWithContext(ctx aws.Context, input *identitystore.ListUsersInput, opts ...request.Option) (*identitystore.ListUsersOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateGroupWithContext(ctx aws.Context, input *identitystore.UpdateGroupInput, opts ...request.Option) (*identitystore.UpdateGroupOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) UpdateUserWithContext(ctx aws.Context, input *identitystore.UpdateUserInput, opts ...request.Option) (*identitystore.UpdateUserOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsForMember(input *identitystore.ListGroupMembershipsForMemberInput) (*identitystore.ListGroupMembershipsForMemberOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsForMemberRequest(input *identitystore.ListGroupMembershipsForMemberInput) (*request.Request, *identitystore.ListGroupMembershipsForMemberOutput) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsForMemberWithContext(ctx aws.Context, input *identitystore.ListGroupMembershipsForMemberInput, opts ...request.Option) (*identitystore.ListGroupMembershipsForMemberOutput, error) {
	return nil, nil
}

func (n *NullIdentityStore) ListGroupMembershipsForMemberPages(input *identitystore.ListGroupMembershipsForMemberInput, fn func(*identitystore.ListGroupMembershipsForMemberOutput, bool) bool) error {
	return nil
}

func (n *NullIdentityStore) ListGroupMembershipsForMemberPagesWithContext(ctx aws.Context, input *identitystore.ListGroupMembershipsForMemberInput, fn func(*identitystore.ListGroupMembershipsForMemberOutput, bool) bool, opts ...request.Option) error {
	return nil
}

func (n *NullIdentityStore) ListGroupMembershipsPagesWithContext(ctx aws.Context, input *identitystore.ListGroupMembershipsInput, fn func(*identitystore.ListGroupMembershipsOutput, bool) bool, opts ...request.Option) error {
	return nil
}

func (n *NullIdentityStore) ListGroupsPagesWithContext(ctx aws.Context, input *identitystore.ListGroupsInput, fn func(*identitystore.ListGroupsOutput, bool) bool, opts ...request.Option) error {
	return nil
}

func (n *NullIdentityStore) ListUsersPagesWithContext(ctx aws.Context, input *identitystore.ListUsersInput, fn func(*identitystore.ListUsersOutput, bool) bool, opts ...request.Option) error {
	return nil
}
