package aws

import (
	"strings"

	"github.com/google/uuid"
)

// virtualIDPrefix is a 10-char lowercase hex string followed by a dash.
// It satisfies the optional prefix group in the AWS Identity Store ID regex:
//
//	([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}
//
// and lets isVirtualID() detect synthetic IDs without shared state between the
// dryClient and DryIdentityStore shims.
const virtualIDPrefix = "deadbeef00-"

// virtualNamespace is the UUIDv5 namespace used to derive all virtual IDs.
// Seeding it from a project-specific URL makes collisions with real IDs negligible.
var virtualNamespace = uuid.NewSHA1(uuid.NameSpaceURL, []byte("ssosync/dry-run"))

// virtualUserID returns a deterministic virtual ID for the given email address.
func virtualUserID(email string) string {
	return virtualIDPrefix + uuid.NewSHA1(virtualNamespace, []byte("user:"+email)).String()
}

// virtualGroupID returns a deterministic virtual ID for the given group display name.
func virtualGroupID(displayName string) string {
	return virtualIDPrefix + uuid.NewSHA1(virtualNamespace, []byte("group:"+displayName)).String()
}

// virtualMembershipID returns a deterministic virtual membership ID for a
// (groupID, userID) pair.
func virtualMembershipID(groupID, userID string) string {
	return virtualIDPrefix + uuid.NewSHA1(virtualNamespace, []byte("membership:"+groupID+":"+userID)).String()
}

// isVirtualID reports whether id was generated by this package's virtual ID helpers.
func isVirtualID(id string) bool {
	return strings.HasPrefix(id, virtualIDPrefix)
}
