AWSTemplateFormatVersion: '2010-09-09'

Description: 
  This CloudFormation template will deploy a an IAM role and some Secrets to 
  allow the CI/CD pipeline in the production account to deploy candidate releases
  (via privately shared app in the AWS Serverless Application Repository (SAR).

Parameters:
  ManagementAccount:
    Description: AWS Account where staging build is automatically deployed and tested
    Type: String
    AllowedPattern: '[0-9]+'

  DelegatedAccount:
    Description: AWS Account where staging build is automatically deployed and tested
    Type: String
    AllowedPattern: '[0-9]+'

  NonDelegatedAccount:
    Description: AWS Account where staging build is automatically deployed and tested
    Type: String
    AllowedPattern: '[0-9]+'

  GoogleCustomerId:
    Type: String
    Description: |
      Google CustomerId, retrieve from https://admin.google.com/ac/accountsettings/profile
    Default: ""
    AllowedPattern: '(?:(?i)C[0-9az]{8})'

  GoogleCredentials:
    Description: Google Workspaces Credentials File, to log into Google (content of credentials.json)
    Type: String
    AllowedPattern: '(\{(\s)*(".*")(\s)*:(\s)*(".*")(\s)*\})'
    NoEcho: true

  GoogleAdminEmail:
    Description: Google Workspaces Admin email
    Type: String
    AllowedPattern: '(([a-zA-Z0-9.+=_-]{0,61})@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*)'      
    NoEcho: true

  SCIMEndpointUrl:
    Description: AWS IAM Identity Center SCIM Endpoint Url
    Type: String
    AllowedPattern: '(?!.*\s)|(https://scim.(us(-gov)?|ap|ca|cn|eu|il|me|mx|sa)-(central|(north|south)?(east|west)?)-([0-9]{1}).amazonaws.com/([A-Za-z0-9]{8,11})-([A-Za-z0-9]{4})-([A-Za-z0-9]{4})-([A-Za-z0-9]{4})-([A-Za-z0-9]{12})/scim/v2/?)'
    NoEcho: true

  SCIMEndpointAccessToken:
    Description: AWS IAM Identity Center SCIM AccessToken
    Type: String
    AllowedPattern: '([0-9a-zA-Z/=+-\\]{500,620})'
    NoEcho: true  

  IdentityStoreId:
    Description: The Id of the Identity Store for the AWS IAM Identity Center instance see (settings page)
    Type: String
    AllowedPattern: "d-[1-z0-9]{10}"
    

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Test Environments
        Parameters:
          - ManagementAccount
          - DelegatedAccount
          - NonDelegatedAccount
      - Label:
          default: Parameters for Google Credentials based authentication, required if either Google Credentials or Both have been selected for Google Authentication Method
        Parameters:
          - GoogleCustomerId
          - GoogleAdminEmail
          - GoogleCredentials
      - Label:
          default: AWS IAM Identity Center
        Parameters:
          - SCIMEndpointUrl
          - SCIMEndpointAccessToken
          - IdentityStoreId
            
    ParameterLabels:
      ManagementAccount:
        default: "What is the account id of the Test Orgs, Management account?"
      DelegatedAccount:
        default: "What is the account id of the Test Orgs, Delegated admin account?"
      NonDelegatedAccount:
        default: "What is the account id of the Test Orgs, Non-delegated admin account?"
      GoogleCustomerId:
        default: "Google CustomerId, retrieve from https://admin.google.com/ac/accountsettings/profile"
      GoogleCredentials:
        default: "contents of credentials.json"
      GoogleAdminEmail:
        default: "admin@WorkspaceDomain"
      SCIMEndpointUrl:
        default: "https://scim.<region>.amazonaws.com/<instance id>/scim/v2/"
      SCIMEndpointAccessToken:
        default: "AWS SSO SCIM Access Token"
      IdentityStoreId:
        default: "The Identity Store Id"

Resources:
  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/SSOSync
      TargetKeyId: !Ref KeyForSecrets

  KeyForSecrets:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Description: Key for protecting SSOSync Secrets in cross-account deployment
      Enabled: true
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: 'kms:*'
          Resource: '*'
        - Sid: DeployRole in Management account
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - kms:Decrypt
            - kms:DescribeKey
          Resource: '*'
        - Sid: DeployRole in Delegated Admin account
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - kms:Decrypt
            - kms:DescribeKey
          Resource: '*'
        - Sid: DeployRole in Non Delegated Admin account
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - kms:Decrypt
            - kms:DescribeKey
          Resource: '*'

  SecretGoogleCustomerId:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineGoogleCustomerId
      SecretString: !Ref GoogleCustomerId
      KmsKeyId: !Ref KeyAlias

  SecretGoogleCustomerIdPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretGoogleCustomerId
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretGoogleCredentials:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineGoogleCredentials
      SecretString: !Ref GoogleCredentials
      KmsKeyId: !Ref KeyAlias

  SecretGoogleCredentialsPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretGoogleCredentials
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretGoogleAdminEmail:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineGoogleAdminEmail
      SecretString: !Ref GoogleAdminEmail
      KmsKeyId: !Ref KeyAlias

  SecretGoogleAdminEmailPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretGoogleAdminEmail
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretSCIMEndpoint: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineSCIMEndpointUrl
      SecretString: !Ref SCIMEndpointUrl
      KmsKeyId: !Ref KeyAlias

  SecretSCIMEndpointPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretSCIMEndpoint
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow      
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretSCIMAccessToken: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineSCIMAccessToken
      SecretString: !Ref SCIMEndpointAccessToken
      KmsKeyId: !Ref KeyAlias

  SecretSCIMAccessTokenPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretSCIMAccessToken
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretRegion: 
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineRegion
      SecretString: !Select [1, !Split [".", !Ref SCIMEndpointUrl]]
      KmsKeyId: !Ref KeyAlias

  SecretRegionPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretRegion
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  SecretIdentityStoreID:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Name: PipelineIdentityStoreId
      SecretString: !Ref IdentityStoreId
      KmsKeyId: !Ref KeyAlias

  SecretIdentityStoreIDPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretIdentityStoreID
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${ManagementAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${DelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${NonDelegatedAccount}:root
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
