AWSTemplateFormatVersion: '2010-09-09'

Description: 
  This CloudFormation template will deploy a an IAM role and some Secrets to 
  allow the CI/CD pipeline in the production account to deploy candidate releases
  (via privately shared app in the AWS Serverless Application Repository (SAR).

Parameters:
  GoogleCredentials:
    Description: Credentials to log into Google (content of credentials.json)
    Type: String
    NoEcho: true
  GoogleAdminEmail:
    Description: Google Workspaces Admin email
    Type: String
    NoEcho: true
  SCIMEndpointUrl:
    Description: AWS IAM Identity Center SCIM Endpoint Url
    Type: String
    NoEcho: true
  SCIMEndpointAccessToken:
    Description: AWS IAM Identity Center SCIM AccessToken
    Type: String
    NoEcho: true  
  Region:
    Description: Region in which IAM Identity Center is deployed
    Type: String
  IdentityStoreId:
    Description: The Id of the Identity Store for the AWS IAM Identity Center instance see (settings page)
    Type: String
    

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Google Workspace
        Parameters:
          - GoogleAdminEmail
          - GoogleCredentials
      - Label:
          default: AWS SSO
        Parameters:
          - SCIMEndpointUrl
          - SCIMEndpointAccessToken
            
    ParameterLabels:
      GoogleCredentials:
        default: "contents of credentials.json"
      GoogleAdminEmail:
        default: "admin@WorkspaceDomain"
      SCIMEndpointUrl:
        default: "https://scim.<region>.amazonaws.com/<instance id>/scim/v2/"
      SCIMEndpointAccessToken:
        default: "AWS SSO SCIM Access Token"
      Region:
        default: "us-east-1"
      IdentityStoreId:
        default: "d-1234567abc"

Resources:
  
  GoogleCredentialSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestGoogleCredentials
      SecretString: !Ref GoogleCredentials

  GoogleAdminEmailSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestGoogleAdminEmail
      SecretString: !Ref GoogleAdminEmail

  SSoSCIMUrlSecret: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestSCIMEndpointUrl
      SecretString: !Ref SCIMEndpointUrl

  SSoSSCIMAccessTokenSecret: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestSCIMAccessToken
      SecretString: !Ref SCIMEndpointAccessToken

  RegionSecret: 
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestRegion
      SecretString: !Ref Region

  IdentityStoreIdSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: TestIdentityStoreId
      SecretString: !Ref IdentityStoreId
