version: 0.2

env:
  exported-variables:
    - AppArn
    - AppVersion

phases:
  install:
    commands:
      # Update sam to latest version
      - wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install --update
      - rm -rf ./sam-installation  aws-sam-cli-linux-x86_64.zip

  pre_build:
    commands:
      # Print all environment variables (handy for AWS CodeBuild logs
      - env

      # Copy in the package file
      - cp ${CODEBUILD_SRC_DIR_Packaged}/packaged-staging.yaml ./packaged.yaml

      # Check we have the required file
      - ls packaged.yaml

  build:
    commands:
      # Create parameters
      - export AppVersion="${GitTag#v}.${GitVersionHash}"
      - aws ssm put-parameter --name "/SSOSync/Staging/Version" --value ${AppVersion} --type String --overwrite

      # remove the previous builds
      #- aws serverlessrepo delete-application --application-id ${AppArn}
        
      # Package our application with AWS SAM
      - echo sam publish --template packaged.yaml --semantic-version ${AppVersion}
      - sam publish --template packaged.yaml --semantic-version ${AppVersion}

      # Share with the StagingAccount
      - aws serverlessrepo put-application-policy --application-id ${AppArn} --statements Principals=${ShareWith},Actions=Deploy
