# .github/workflows/quickstarts.yaml
name: quickstarts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Fetch SEMANTIC_VERSION
        run : |
          echo "SEMANTIC_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Show SemanticVersion
        run: |
          echo "env.SemanticVersion: ${{ env.SEMANTIC_VERSION }}"

      - name: Show current SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml

      - name: Update Templates
        run: |
          git grep -lr -e 'SemanticVersion' -- quick-start | xargs sed -i -E 's/SemanticVersion: [0-9.]+/SemanticVersion: ${{ env.SEMANTIC_VERSION }}/g'

      - name: Show Templates SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml

      - name: Commit updated Quick Start Templates
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update Quick Start templates
          file_pattern: quick-start
