# .github/workflows/release.yaml
name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Update version strings
        run: |
          SemanticVersion="${GITHUB_REF#refs/tags/v}"
          sed -i '' -E "s/SemanticVersion: [0-9.]+/SemanticVersion: $SemanticVersion/g" quick-start/*.yaml template.yaml

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache development tools
        uses: actions/cache@v4
        with:
          path: .bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Run CI pipeline
        run: make test-coverage
        
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 30

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache development tools
        uses: actions/cache@v4
        with:
          path: .bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-
          
      - name: Create release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quickstart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Fetch SEMANTIC_VERSION
        run : |
          echo "SEMANTIC_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Show SemanticVersion
        run: echo "env.SemanticVersion: ${{ env.SEMANTIC_VERSION }}"

      - name: Show current SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml
      - name: Update Templates
        run: |
          git grep -lr -e 'SemanticVersion' -- quick-start | xargs sed -i -E 's/SemanticVersion: [0-9.]+/SemanticVersion: ${{ env.SEMANTIC_VERSION }}/g'
      - name: Show Templates SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml

      - name: Commit updated Quick Start Templates
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update Quick Start templates
          file_pattern: quick-start
