# .github/workflows/release-publish.yaml
name: "Post Release Updates"

on:
    release:
    types: [released]

permissions:
  contents: write
  id-token: write

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          # Value already defaults to true, but `persist-credentials` is required to push new commits to the repository.
          persist-credentials: true

      - name: Fetch SEMANTIC_VERSION
        run: |
          echo "SEMANTIC_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Show SemanticVersion
        run: |
          echo "env.SemanticVersion: ${{ env.SEMANTIC_VERSION }}"

      - name: Show current SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml

      - name: Update Templates
        run: |
          git grep -lr -e 'SemanticVersion' -- quick-start | xargs sed -i -E 's/SemanticVersion: [0-9.]+/SemanticVersion: ${{ env.SEMANTIC_VERSION }}/g'

      - name: Show Templates SemanticVersion
        run: grep SemanticVersion quick-start/*.yaml

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: master
          commit_message: Update CHANGELOG and Quick Start templates
          file_pattern: 'CHANGELOG.md quick-start'